name: normal

on:
  push:
    branches:
      - main

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@main
      - name: Build x86 image
        uses: elgohr/Publish-Docker-Github-Action@main
        with:
          name: ehco1996/v2scar
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tags: "latest"
          dockerfile: Dockerfile
