name: normal

on:
  push:
    branches:
      - master

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
      - name: Build x86 image
        uses: elgohr/Publish-Docker-Github-Action@v4
